### ISSUE TITLE
mock completion for the plugin

### ISSUE THREAD

**Issue by huafu** [cspotcode/ts-plugin-jest-hoist#1]
Hi @cspotcode, trying to reach you on slack but no answer, saw that you prefer here so I created a dummy issue...

I'm trying to provide typing completion for mocked imports thanks to a lang service plugin in ts-jest... so far all good, I've collected all `ImportDeclaration` and `ExpressionStatement` which correspond to `jest.mock` or `jest.doMock` in a `SourceFile`. But I'm stuck here. Is it possible to override the type of variable in a plugin? if so, how? Trying to find info on the internet with no luck at all. Also looked at TS sources a bit... got lost :-D

I do have a `MockedDeep<X>` TS type which, applied to the `typeof someImport` provides full completion, but how to override the type of `import someImport from X` within a language plugin... do you know? I'll also try to search on typescript issues...

I first thought I'd upgrade `getCompletionsAtPosition` but then once jest API changes I have to change too, and tslint for example will continue to bail as `someImport has no import mockReset` for example...

**Comment by huafu** [comment]
Long story short, it's not possible... https://github.com/Microsoft/TypeScript/issues/27153

**Comment by cspotcode** [comment]
Is this for development in this repo or over in ts-jest?  Sounds like it's for the latter, so let's track it over there.  The point is to keep discussion in a place where everyone can read and benefit from it.  That's one of the primary reasons I prefer this over private Slack chats.  And presumably there is already an issue or PR that tracks this work.  @ mentions on all Github repositories land in the same inbox.

If you're asking advice for writing a PR against this repo, then we can reopen this issue.

**Comment by huafu** [comment]
I totally got your point with GtiHub. What I wanted to do is NOT possible anyway ;-)
